Repository kustaurant/BackEnd-integration, pull requests merged in 2025-09, with the labels that each got.

#87 [refactor] 식당 조회 레이어 리팩토링
  src/main/java/com/kustaurant/kustaurant/global/config/WebMvcConfig.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/chart/controller/RestaurantChartApiController.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/chart/controller/RestaurantChartApiDoc.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/chart/controller/RestaurantChartController.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/chart/service/RestaurantChartService.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/chart/service/port/RestaurantChartRepository.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/argument_resolver/ChartCond.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/argument_resolver/ChartCondArgumentResolver.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/argument_resolver/CuisineList.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/argument_resolver/CuisineListArgumentResolver.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/argument_resolver/LocationListArgumentResolver.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/argument_resolver/SituationList.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/argument_resolver/SituationListArgumentResolver.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/dto/ChartCondition.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/infrastructure/query/RestaurantChartQuery.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/infrastructure/repository/RestaurantChartRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/infrastructure/repository/RestaurantCommonExpressions.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/infrastructure/repository/RestaurantCoreInfoRepository.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/infrastructure/repository/RestaurantDrawRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/infrastructure/repository/RestaurantHomeRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/infrastructure/repository/RestaurantQueryRepository.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/common/infrastructure/repository/RestaurantSearchRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/draw/DrawApiController.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/draw/DrawApiDoc.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/draw/DrawController.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/draw/RestaurantDrawRepository.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/draw/RestaurantDrawService.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/home/RestaurantHomeRepository.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/home/RestaurantHomeService.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/search/RestaurantSearchRepository.java
  src/main/java/com/kustaurant/kustaurant/restaurant/query/search/RestaurantSearchService.java
  src/main/java/com/kustaurant/kustaurant/user/login/api/controller/test/NaverCallbackController.java
  src/main/java/com/kustaurant/kustaurant/v1/evaluation/EvaluationV1Controller.java
  src/main/java/com/kustaurant/kustaurant/v1/restaurant/HomeV1Controller.java
  src/main/java/com/kustaurant/kustaurant/v1/restaurant/RestaurantV1Controller.java
  src/main/java/com/kustaurant/kustaurant/v1/restaurant/TierV1Controller.java
  src/main/java/com/kustaurant/kustaurant/v1/restaurant/TierV1Doc.java
  src/test/java/com/kustaurant/kustaurant/restaurant/query/chart/service/RestaurantChartServiceTest.java
Labels: refactor, 김성운

#88 Feature/monitoring 모니터링 도입
  .github/workflows/discord-pr.yml
  .github/workflows/pre-test.yml
  .gitignore
  build.gradle
  docker-compose.yml
  monitoring/grafana/dashboards/jvm.json
  monitoring/grafana/dashboards/springBoot.json
  monitoring/grafana/provisioning/dashboards/dashboards.yml
  monitoring/grafana/provisioning/datasources/datasource.yml
  monitoring/loki/config.yml
  monitoring/prometheus.yml
  monitoring/promtail/config.yml
  src/main/java/com/kustaurant/kustaurant/common/discordAlert/AlertRateLimiter.java
  src/main/java/com/kustaurant/kustaurant/common/discordAlert/DiscordNotifier.java
  src/main/java/com/kustaurant/kustaurant/common/discordAlert/OpsTestController.java
  src/main/java/com/kustaurant/kustaurant/common/discordAlert/RequestSnapshot.java
  src/main/java/com/kustaurant/kustaurant/common/discordAlert/RequestTracingFilter.java
  src/main/java/com/kustaurant/kustaurant/global/config/alert/AlertAsyncConfig.java
  src/main/java/com/kustaurant/kustaurant/global/config/jpa/JpaAuditingConfig.java
  src/main/java/com/kustaurant/kustaurant/global/exception/ApiErrorResponse.java
  src/main/java/com/kustaurant/kustaurant/global/exception/advice/GlobalExceptionRestHandler.java
  src/main/java/com/kustaurant/kustaurant/global/exception/advice/GlobalExceptionWebHandler.java
  src/main/resources/application.yml
Labels: AI Review Request

#100 [feat] 스프링 로그
  .github/workflows/deploy.yml
  .gitignore
  infra/docker/kustaurant/docker-compose.prod.yml
  infra/monitoring/grafana/dashboards/springBoot.json
  infra/monitoring/promtail/config.yml
  server/kustaurant/build.gradle
  server/kustaurant/src/main/resources/logback-spring.xml
Labels: enhancement

#101 그라파나 스프링 로그 출력
  .github/workflows/deploy.yml
  .github/workflows/discord-pr.yml
  .gitignore
  infra/docker/kustaurant/docker-compose.prod.yml
  infra/monitoring/grafana/dashboards/springBoot.json
  infra/monitoring/promtail/config.yml
  server/kustaurant/build.gradle
  server/kustaurant/src/main/java/com/kustaurant/kustaurant/restaurant/restaurant/controller/RestaurantController.java
  server/kustaurant/src/main/resources/logback-spring.xml
  server/kustaurant/src/main/resources/templates/restaurant/restaurant.html
Labels: enhancement
