Repository kustaurant/BackEnd-integration, pull requests merged in 2025-04, with the labels that each got.

#33 [Refactor] 티어표 기능 정상화 + 컨트롤러 티어관련 로직을 티어 서비스 안으로 옮기기
  src/main/java/com/kustaurant/kustaurant/api/restaurant/RestaurantTierApiController.java
  src/main/java/com/kustaurant/kustaurant/common/evaluation/infrastructure/evaluation/EvaluationJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/common/evaluation/infrastructure/evaluation/EvaluationRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/common/evaluation/service/port/EvaluationRepository.java
  src/main/java/com/kustaurant/kustaurant/common/restaurant/domain/dto/RestaurantTierDTO.java
  src/main/java/com/kustaurant/kustaurant/common/restaurant/infrastructure/restaurant/RestaurantJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/common/restaurant/infrastructure/restaurant/RestaurantRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/common/restaurant/service/RestaurantApiService.java
  src/main/java/com/kustaurant/kustaurant/common/restaurant/service/RestaurantTierService.java
  src/main/java/com/kustaurant/kustaurant/common/restaurant/service/port/RestaurantRepository.java
  src/main/java/com/kustaurant/kustaurant/web/restaurant/RestaurantTierWebController.java
  src/main/java/com/kustaurant/kustaurant/web/restaurant/RestaurantWebService.java
  src/main/resources/templates/tier.html
Labels: refactor, 김성운

#35 [Refactor] modal과 notice 리팩토링
  src/main/java/com/kustaurant/kustaurant/common/modal/infrastructure/HomeModalEntity.java
  src/main/java/com/kustaurant/kustaurant/common/modal/infrastructure/HomeModalRepository.java
  src/main/java/com/kustaurant/kustaurant/common/modal/service/HomeModalService.java
  src/main/java/com/kustaurant/kustaurant/common/notice/controller/NoticeController.java
  src/main/java/com/kustaurant/kustaurant/common/notice/domain/NoticeDTO.java
  src/main/java/com/kustaurant/kustaurant/common/notice/infrastructure/NoticeEntity.java
  src/main/java/com/kustaurant/kustaurant/common/notice/service/NoticeService.java
  src/main/java/com/kustaurant/kustaurant/common/user/service/MypageApiService.java
  src/main/java/com/kustaurant/kustaurant/web/restaurant/MainController.java
  src/main/resources/static/js/homeScript.js
  src/main/resources/templates/footer.html
  src/main/resources/templates/home.html
  src/main/resources/templates/notice.html
  src/test/java/com/kustaurant/kustaurant/common/modal/service/HomeModalServiceTest.java
  src/test/java/com/kustaurant/kustaurant/common/notice/service/NoticeServiceTest.java
  src/test/java/com/kustaurant/kustaurant/common/restaurant/service/RestaurantFavoriteServiceTest.java
Labels: refactor, test, 심경보

#39 Feature/flyway
  .gitignore
  build.gradle
  src/main/java/com/kustaurant/kustaurant/global/config/flywayRepairConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/auth.yml
  src/main/resources/db/migration/local/V0__init_dummy.sql
  src/main/resources/db/migration/prod/V0__init_dummy.sql
Labels: 심경보
