Repository kustaurant/BackEnd-integration, pull requests merged in 2025-07, with the labels that each got.

#56 fix: 개발 DB 재구축 및 flyway 재설정
  src/main/java/com/kustaurant/kustaurant/global/exception/ErrorCode.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentDislikeEntity.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentEntity.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentLikeEntity.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/post/post/domain/dto/PostDTO.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/entity/PostDislikeEntity.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/entity/PostLikeEntity.java
  src/main/java/com/kustaurant/kustaurant/user/user/infrastructure/UserEntity.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/local/V0__init_dummy.sql
  src/main/resources/db/migration/local/V2__post_breaking_down_manytomany.sql
  src/main/resources/db/migration/local/V2__while_login_refactoring.sql
  src/main/resources/db/migration/local/V3__post_breaking_down_manytomany.sql
  src/main/resources/db/migration/local/V4__post_column_changed.sql
  src/main/resources/db/migration/local/V5__update_users_tbl_status_enum_and_remove_tokens.sql
  src/main/resources/db/migration/local/V6__alter_fk_userId_int_to_bigint.sql
  src/main/resources/db/migration/local/V7__create_user_stats_tbl.sql
  src/main/resources/db/migration/local/V8__alter_evaluation_pk_to_bigint.sql
  src/main/resources/db/migration/prod/V0__init_dummy.sql
  src/main/resources/templates/community.html
  src/main/resources/templates/community_post.html
Labels: bug

#57 refactor: 커뮤니티 관련 모든 엔티티 연관관계 매핑 객체 참조에서 id 기반 참조 로 변경
  src/main/java/com/kustaurant/kustaurant/post/comment/controller/api/PostApiCommentService.java
  src/main/java/com/kustaurant/kustaurant/post/comment/controller/web/PostCommentService.java
  src/main/java/com/kustaurant/kustaurant/post/comment/domain/PostComment.java
  src/main/java/com/kustaurant/kustaurant/post/comment/domain/PostCommentDislike.java
  src/main/java/com/kustaurant/kustaurant/post/comment/domain/PostCommentLike.java
  src/main/java/com/kustaurant/kustaurant/post/comment/dto/CommentLikeDislikeDTO.java
  src/main/java/com/kustaurant/kustaurant/post/comment/dto/PostCommentDTO.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentApiRepository.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentDislikeEntity.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentDislikeJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentDislikeRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentEntity.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentLikeEntity.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentLikeJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentLikeRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/post/comment/infrastructure/PostCommentRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/post/comment/service/port/PostCommentDislikeRepository.java
  src/main/java/com/kustaurant/kustaurant/post/comment/service/port/PostCommentLikeRepository.java
  src/main/java/com/kustaurant/kustaurant/post/comment/service/port/PostCommentRepository.java
  src/main/java/com/kustaurant/kustaurant/post/post/controller/CommunityApiController.java
  src/main/java/com/kustaurant/kustaurant/post/post/domain/Post.java
  src/main/java/com/kustaurant/kustaurant/post/post/domain/PostDislike.java
  src/main/java/com/kustaurant/kustaurant/post/post/domain/PostLike.java
  src/main/java/com/kustaurant/kustaurant/post/post/domain/PostPhoto.java
  src/main/java/com/kustaurant/kustaurant/post/post/domain/dto/PostDTO.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/PostDislikeRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/PostLikeRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/PostPhotoRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/PostRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/entity/PostDislikeEntity.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/entity/PostEntity.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/entity/PostLikeEntity.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/entity/PostPhotoEntity.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/repositoryInterface/PostDislikeJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/repositoryInterface/PostJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/repositoryInterface/PostLikeJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/post/post/infrastructure/repositoryInterface/PostPhotoJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/post/post/service/api/PostApiService.java
  src/main/java/com/kustaurant/kustaurant/post/post/service/port/PostDislikeRepository.java
  src/main/java/com/kustaurant/kustaurant/post/post/service/port/PostPhotoRepository.java
  src/main/java/com/kustaurant/kustaurant/post/post/service/port/PostRepository.java
  src/main/java/com/kustaurant/kustaurant/post/post/service/web/PostService.java
  src/main/java/com/kustaurant/kustaurant/user/mypage/infrastructure/queryRepo/MyPostCommentQueryRepository.java
  src/main/java/com/kustaurant/kustaurant/user/mypage/infrastructure/queryRepo/MyPostQueryRepository.java
  src/main/java/com/kustaurant/kustaurant/user/mypage/infrastructure/queryRepo/MyPostScrapQueryRepository.java
  src/main/java/com/kustaurant/kustaurant/user/mypage/service/MypageApiService.java
  src/main/java/com/kustaurant/kustaurant/user/mypage/service/MypageServiceImpl.java
  src/main/java/com/kustaurant/kustaurant/user/user/infrastructure/UserEntity.java
  src/test/java/com/kustaurant/kustaurant/mock/FakePostRepository.java
Labels: refactor

#65 [Refactor] 식당 상세 화면 리뷰 기능 수정
  build.gradle
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/controller/api/EvalCommentApiController.java
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/controller/port/EvalCommUserReactionService.java
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/controller/request/EvalCommentRequest.java
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/controller/web/EvalCommUserReactionWebController.java
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/controller/web/EvalCommentWebController.java
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/infrastructure/repo/EvalCommentRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/infrastructure/repo/jpa/EvalCommentJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/service/EvalCommCommandServiceImpl.java
  src/main/java/com/kustaurant/kustaurant/evaluation/comment/service/EvalCommUserReactionServiceImpl.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/controller/web/EvalUserReactionWebController.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/controller/web/EvaluationWebController.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/infrastructure/EvaluationCommandRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/infrastructure/EvaluationQueryRepositoryImpl.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/infrastructure/entity/EvalUserReactionEntity.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/infrastructure/entity/EvaluationEntity.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/infrastructure/jpa/EvalUserReactionRepository.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/infrastructure/jpa/EvaluationQueryJpaRepository.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/service/EvalUserReactionService.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/service/port/EvaluationCommandRepository.java
  src/main/java/com/kustaurant/kustaurant/evaluation/evaluation/service/port/EvaluationQueryRepository.java
  src/main/java/com/kustaurant/kustaurant/evaluation/review/ReviewQueryService.java
  src/main/java/com/kustaurant/kustaurant/evaluation/review/ReviewWebController.java
  src/main/java/com/kustaurant/kustaurant/global/config/security/SecurityWebConfig.java
  src/main/java/com/kustaurant/kustaurant/global/exception/advice/GlobalExceptionWebHandler.java
  src/main/java/com/kustaurant/kustaurant/home/MainController.java
  src/main/resources/static/css/restaurant-style.css
  src/main/resources/static/js/restaurantReviewScript.js
  src/main/resources/static/js/restaurantScript.js
  src/main/resources/templates/restaurant.html
  src/test/java/com/kustaurant/kustaurant/mock/FakeEvaluationQueryRepository.java
  src/test/java/com/kustaurant/kustaurant/mock/FakeEvaluationRepository.java
Labels: refactor, AI Review Request

#71 chore: Java 버전 21로 업그레이드 및 테스트 자동화 추가
  .github/workflows/pre-test.yml
  build.gradle
  settings.gradle
  src/test/java/com/kustaurant/kustaurant/post/PostCommentServiceTest.java
  src/test/java/com/kustaurant/kustaurant/user/mypage/service/MypageApiServiceIT.java
  src/test/java/com/kustaurant/kustaurant/user/service/UserServiceImplTest.java
Labels: test, 심경보

#72 [fix] PostCommentServiceTest 테스트 오류 수정
  src/test/java/com/kustaurant/kustaurant/post/PostCommentServiceTest.java
Labels: 임재형
